package com.google.gwt.sample.stockwatcher.entity;

// Generated 2013/01/13 13:40:52 by Hibernate Tools 3.4.0.CR1

/**
 * UserOnetoone generated by hbm2java
 */
public class AddressUser implements java.io.Serializable {

	private long userId;
	private Address homeAddress;
	private Address billingAddress;
	private String username;
	private Long version;

	public AddressUser() {
	}

	public AddressUser(long userId) {
		this.userId = userId;
	}

	public AddressUser(long userId, Address addressOnetoone,
			String username) {
		this.userId = userId;
		this.homeAddress = addressOnetoone;
		this.username = username;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public Address getHomeAddress() {
		return this.homeAddress;
	}

	public void setHomeAddress(Address address) {
		this.homeAddress = address;
	}

	public Address getBillingAddress() {
		return billingAddress;
	}

	public void setBillingAddress(Address billingAddress) {
		this.billingAddress = billingAddress;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
}
